server.port=${PORT:8081}

spring.datasource.url=jdbc:postgresql://ep-steep-credit-antqaxic-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vte27sKYgOyj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Add your Gemini API Key here so the AI works for EVERYTHING you ask!
# Get a free key at: https://aistudio.google.com/app/apikey
#google.ai.api.key=